apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
