apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.name }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
